name: Issue report
description: Report an issue
labels: [bug, need repro]
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Please provide us with the issue you are facing
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Issue priority
      description: Please be realistic. If you need to elaborate on your reasoning, please use the issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
